(	( ( (row("Issuer").ToString.ToLower.Contains("commercial mortgage") And Not row("Issuer").ToString.ToLower.Contains("alternative")) Or row("CMBS Type").ToString.ToLower.Contains("conduit") Or row("CMBS
Type").ToString.ToLower.Contains("fusion") Or row("Security Type").ToString="CMBS") ) And Not row("Mortgage Type (Remics)").ToString.ToUpper="IO" And ( ( Not row("S&P Rating").ToString.Trim="" Or Not row( "S&P
Rating").GetType.ToString.Contains("System.Int") Or Not row("S&P Rating").GetType.ToString.Contains("System.Doub") Or Not row("S&P Rating").ToString.ToLower.Contains("aaa") ) And ( Not row("Moody Rating").ToString.
Trim="" Or Not row("Moody Rating").GetType.ToString.Contains("System.Int") Or Not row("Moody Rating").GetType.ToString.Contains("System.Doub") Or Not row("Moody Rating").ToString.ToLower. Contains("aaa") ) And (
Not row("Fitch Rating").ToString.Trim="" Or Not row("Fitch Rating").GetType.ToString.Contains("System.Int") Or Not row("Fitch Rating").GetType.ToString.Contains("System.Doub") Or Not row("Fitch Rating").ToString.
ToLower.Contains("aaa") ) ) And ( ( row("S&P Rating").ToString.ToLower="aa" Or row("S&P Rating").ToString.ToLower="aa+" Or row("S&P Rating").ToString.ToLower="aa-" Or row("S&P Rating").ToString.ToLower="a+" Or row(
"S&P Rating").ToString.ToLower="a" Or row("S&P Rating").ToString.ToLower="a-" ) Or ( row("Moody Rating").ToString.ToLower= "aa1" Or row("Moody Rating").ToString.ToLower = "aa2" Or row("Moody Rating").ToString.
ToLower= "aa3" Or row("Moody Rating").ToString.ToLower= "a1" Or row("Moody Rating").ToString.ToLower= "a2" Or row("Moody Rating").ToString.ToLower= "a3" ) Or ( row( "Fitch Rating").ToString.ToLower="aa" Or row(
"Fitch Rating").ToString.ToLower="aa+" Or row("Fitch Rating").ToString.ToLower="aa-" Or row("Fitch Rating").ToString.ToLower="a+" Or row("Fitch Rating").ToString .ToLower="a" Or row("Fitch Rating").ToString.ToLower
="a-" ) ) )